name: Mirror Website

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-mirror]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout MineBuilders/.github repository (source repository)
        uses: actions/checkout@v2
        with:
          repository: MineBuilders/.github
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: minebuilders.github.io
