name: Mirror Website

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the .github repository (source repository)
        uses: actions/checkout@v2
        with:
          repository: MineBuilders/.github
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push to minebuilders.github.io
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Mirror website from .github repository"
          git push origin main
